replicaCount: 1
node_env: development

image: ghost:latest

url: ghost.k8s.local
service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  ingressClass: traefik

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi

