apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "my-ghost.fullname" . }}
  labels:
    {{- include "my-ghost.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "my-ghost.selectorLabels" . | nindent 6}}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "my-ghost.selectorLabels" . | nindent 8}}
    spec:
      volumes:
      - name: ghost-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "my-ghost.fullname" .) }}
      {{- else }}
      emptyDir: {}
      {{ end }}
      containers:
        - name: ghost-app
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: ghost-data
            mountPath: /var/lib/ghost/content
          ports:
            - containerPort: 2368
          env:
            - name: NODE_ENV
              value: {{ .Values.node_env | default "production" }}
            {{- if .Values.url }}
            - name: url
              value: http://{{ .Values.url }}
            {{- end }}
            - name: database__connection__filename
              value: '/var/lib/ghost/content/data/ghost.db'
