apiVersion: v1
kind: Service
metadata:
  name: {{ template "my-ghost.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "my-ghost.selectorLabels" . | nindent 4}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 2368
      {{- if (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      {{- end }}
